// Mocks generated by Mockito 5.4.2 from annotations
// in blinq/test/presentation/contacts/editors/premade_message/bloc/premade_message_edit_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:blinq/data/model/premade_message/premade_message_response_dto.dart'
    as _i2;
import 'package:blinq/data/model/premade_message/request/premade_message_request_model.dart'
    as _i7;
import 'package:blinq/data/model/premade_message/response/premade_message_response_model.dart'
    as _i3;
import 'package:blinq/domain/repositories/premade_messages_repository.dart'
    as _i4;
import 'package:blinq/presentation/contacts/pages/premade_messages/bloc/premade_messages_bloc.dart'
    as _i5;
import 'package:blinq/presentation/contacts/pages/premade_messages/bloc/premade_messages_event.dart'
    as _i8;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePreMadeMessageResponseDto_0 extends _i1.SmartFake
    implements _i2.PreMadeMessageResponseDto {
  _FakePreMadeMessageResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreMadeMessageResponseModel_1 extends _i1.SmartFake
    implements _i3.PreMadeMessageResponseModel {
  _FakePreMadeMessageResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePremadeMessagesRepository_2 extends _i1.SmartFake
    implements _i4.PremadeMessagesRepository {
  _FakePremadeMessagesRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreMadeMessagesState_3 extends _i1.SmartFake
    implements _i5.PreMadeMessagesState {
  _FakePreMadeMessagesState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PremadeMessagesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremadeMessagesRepository extends _i1.Mock
    implements _i4.PremadeMessagesRepository {
  MockPremadeMessagesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PreMadeMessageResponseDto> fetchList() => (super.noSuchMethod(
        Invocation.method(
          #fetchList,
          [],
        ),
        returnValue: _i6.Future<_i2.PreMadeMessageResponseDto>.value(
            _FakePreMadeMessageResponseDto_0(
          this,
          Invocation.method(
            #fetchList,
            [],
          ),
        )),
      ) as _i6.Future<_i2.PreMadeMessageResponseDto>);

  @override
  _i6.Future<_i3.PreMadeMessageResponseModel> add(
          _i7.PreMadeMessageRequestModel? premadeMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [premadeMessage],
        ),
        returnValue: _i6.Future<_i3.PreMadeMessageResponseModel>.value(
            _FakePreMadeMessageResponseModel_1(
          this,
          Invocation.method(
            #add,
            [premadeMessage],
          ),
        )),
      ) as _i6.Future<_i3.PreMadeMessageResponseModel>);

  @override
  _i6.Future<_i3.PreMadeMessageResponseModel> update({
    required int? id,
    required _i7.PreMadeMessageRequestModel? premadeMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #id: id,
            #premadeMessage: premadeMessage,
          },
        ),
        returnValue: _i6.Future<_i3.PreMadeMessageResponseModel>.value(
            _FakePreMadeMessageResponseModel_1(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #premadeMessage: premadeMessage,
            },
          ),
        )),
      ) as _i6.Future<_i3.PreMadeMessageResponseModel>);

  @override
  _i6.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [PreMadeMessagesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreMadeMessagesBloc extends _i1.Mock
    implements _i5.PreMadeMessagesBloc {
  MockPreMadeMessagesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PremadeMessagesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePremadeMessagesRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.PremadeMessagesRepository);

  @override
  _i5.PreMadeMessagesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePreMadeMessagesState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.PreMadeMessagesState);

  @override
  _i6.Stream<_i5.PreMadeMessagesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i5.PreMadeMessagesState>.empty(),
      ) as _i6.Stream<_i5.PreMadeMessagesState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void onEditPressed({int? id}) => super.noSuchMethod(
        Invocation.method(
          #onEditPressed,
          [],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i8.PreMadeMessagesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i8.PreMadeMessagesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.PreMadeMessagesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i8.PreMadeMessagesEvent>(
    _i9.EventHandler<E, _i5.PreMadeMessagesState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i8.PreMadeMessagesEvent, _i5.PreMadeMessagesState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onChange(_i9.Change<_i5.PreMadeMessagesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
