// Mocks generated by Mockito 5.4.2 from annotations
// in blinq/test/bloc/login/login.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:blinq/data/datasource/local/auth_local_db.dart' as _i8;
import 'package:blinq/data/datasource/remote/auth_api.dart' as _i4;
import 'package:blinq/data/model/login/google_request/login_google_request.dart'
    as _i7;
import 'package:blinq/data/model/login/response/login_response_model.dart'
    as _i2;
import 'package:blinq/data/model/registration/registration_request_dto.dart'
    as _i6;
import 'package:blinq/data/model/send_email/response/send_email_response.dart'
    as _i3;
import 'package:blinq/data/model/user/user_status.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseModel_0 extends _i1.SmartFake
    implements _i2.LoginResponseModel {
  _FakeLoginResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendEmailResponse_1 extends _i1.SmartFake
    implements _i3.SendEmailResponse {
  _FakeSendEmailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i4.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LoginResponseModel> login({
    required String? mail,
    required String? password,
    required String? deviceType,
    required String? fcmToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #mail: mail,
            #password: password,
            #deviceType: deviceType,
            #fcmToken: fcmToken,
          },
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #mail: mail,
              #password: password,
              #deviceType: deviceType,
              #fcmToken: fcmToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseModel>);

  @override
  _i5.Future<_i2.LoginResponseModel> register(
          {required _i6.RegistrationRequestDto? registrationRequestDto}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#registrationRequestDto: registrationRequestDto},
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #register,
            [],
            {#registrationRequestDto: registrationRequestDto},
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseModel>);

  @override
  _i5.Future<_i3.SendEmailResponse> sendEmail(String? mail) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [mail],
        ),
        returnValue:
            _i5.Future<_i3.SendEmailResponse>.value(_FakeSendEmailResponse_1(
          this,
          Invocation.method(
            #sendEmail,
            [mail],
          ),
        )),
      ) as _i5.Future<_i3.SendEmailResponse>);

  @override
  _i5.Future<_i2.LoginResponseModel> loginWithApple({
    required String? token,
    required String? deviceType,
    required String? fcmToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithApple,
          [],
          {
            #token: token,
            #deviceType: deviceType,
            #fcmToken: fcmToken,
          },
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #loginWithApple,
            [],
            {
              #token: token,
              #deviceType: deviceType,
              #fcmToken: fcmToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseModel>);

  @override
  _i5.Future<_i2.LoginResponseModel> loginWithGoogle(
          _i7.LoginGoogleRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithGoogle,
          [request],
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #loginWithGoogle,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseModel>);

  @override
  _i5.Future<void> getVerificationCode(String? mail) => (super.noSuchMethod(
        Invocation.method(
          #getVerificationCode,
          [mail],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> confirmMailVerification({
    required String? mail,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmMailVerification,
          [],
          {
            #mail: mail,
            #code: code,
          },
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> resetPassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [newPassword],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verifyDeleteUser(String? code) => (super.noSuchMethod(
        Invocation.method(
          #verifyDeleteUser,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.LoginResponseModel> refreshToken(String? refresh) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refresh],
        ),
        returnValue:
            _i5.Future<_i2.LoginResponseModel>.value(_FakeLoginResponseModel_0(
          this,
          Invocation.method(
            #refreshToken,
            [refresh],
          ),
        )),
      ) as _i5.Future<_i2.LoginResponseModel>);
}

/// A class which mocks [AuthLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalStorage extends _i1.Mock implements _i8.AuthLocalStorage {
  MockAuthLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setUserStatus(_i9.UserStatus? userStatus) => super.noSuchMethod(
        Invocation.method(
          #setUserStatus,
          [userStatus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.UserStatus getUserStatus() => (super.noSuchMethod(
        Invocation.method(
          #getUserStatus,
          [],
        ),
        returnValue: _i9.UserStatus.newUser,
      ) as _i9.UserStatus);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: '',
      ) as String);

  @override
  void setRefreshToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setRefreshToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: '',
      ) as String);

  @override
  void setUserName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getUserName() => (super.noSuchMethod(
        Invocation.method(
          #getUserName,
          [],
        ),
        returnValue: '',
      ) as String);

  @override
  void setUserId(int? id) => super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void setUserPhone(String? phone) => super.noSuchMethod(
        Invocation.method(
          #setUserPhone,
          [phone],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getUserPhone() => (super.noSuchMethod(
        Invocation.method(
          #getUserPhone,
          [],
        ),
        returnValue: '',
      ) as String);
}
