// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqKZVTLo5hc3AsO2TCfww1sLjz_BGyxMs',
    appId: '1:573054971190:android:0295a0504ce0d5e0369797',
    messagingSenderId: '573054971190',
    projectId: 'blinq-382713',
    storageBucket: 'blinq-382713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzByU5KEJyq-ED6jVLcX8lRmNg3GMbi8I',
    appId: '1:573054971190:ios:aa81edef6d9e69e5369797',
    messagingSenderId: '573054971190',
    projectId: 'blinq-382713',
    storageBucket: 'blinq-382713.appspot.com',
    androidClientId: '573054971190-lhnt6afnkg0pr3r9h03pgnlv1eh6n15r.apps.googleusercontent.com',
    iosClientId: '573054971190-inud9nk3kcpnsgfam3ukadmu5trk45d6.apps.googleusercontent.com',
    iosBundleId: 'com.samuraidevs.blinq',
  );
}
