// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwiakRNMRGovAmDz8avteVAXkBCS9vuWE',
    appId: '1:525019772489:android:80872533f67cbea9b1f198',
    messagingSenderId: '525019772489',
    projectId: 'new-blinq',
    storageBucket: 'new-blinq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn35c-O1vEFyL8qjQjPETP2NetJdwDcng',
    appId: '1:525019772489:ios:fdcda5731500632bb1f198',
    messagingSenderId: '525019772489',
    projectId: 'new-blinq',
    storageBucket: 'new-blinq.firebasestorage.app',
    androidClientId: '525019772489-f8pketspi66un5rs093odiek4mict2iu.apps.googleusercontent.com',
    iosClientId: '525019772489-1j4it7akgsebav2erpmbtj231vkhp4ej.apps.googleusercontent.com',
    iosBundleId: 'com.samuraidevs.blinq',
  );
}
