part of 'damaged_parts_bloc.dart';

List<String> _carsSelect = [
  AppDrawables.carFront,
  AppDrawables.carLeft,
  AppDrawables.carRight,
  AppDrawables.carTop,
  AppDrawables.carBack,
];

List<String> _blankCarsSelect = [
  AppDrawables.blankCarFront,
  AppDrawables.blankCarLeft,
  AppDrawables.blankCarRight,
  AppDrawables.blankCarTop,
  AppDrawables.blankCarBack,
];

List<String> _vanSelect = [
  AppDrawables.vanFront,
  AppDrawables.vanLeft,
  AppDrawables.vanRight,
  AppDrawables.vanTop,
  AppDrawables.vanBack,
];

List<String> _blankVanSelect = [
  AppDrawables.vanFront,
  AppDrawables.blankVanLeft,
  AppDrawables.blankVanRight,
  AppDrawables.vanTop,
  AppDrawables.vanBack,
];

List<String> _motoSelect = [
  AppDrawables.motoFront,
  AppDrawables.motoLeft,
  // AppDrawables.motoRight,
];

List<String> _carPartList = [
  'auto.capot'.tr(),
  'auto.windscreen'.tr(),
  'auto.roof'.tr(),
  'auto.rear window'.tr(),
  'auto.car trunk'.tr(),
  'auto.rear left headlight'.tr(),
  'auto.rear right headlight'.tr(),
  'auto.Rear bumpers'.tr(),
  'auto.right side view mirror'.tr(),
  'auto.left side view mirror'.tr(),
  'auto.front right headlight'.tr(),
  'auto.front left headlight'.tr(),
  'auto.front grille'.tr(),
  'auto.front bumpers'.tr(),
  'auto.rear right window'.tr(),
  'auto.front right window'.tr(),
  'auto.front right door'.tr(),
  'auto.rear right door'.tr(),
  'auto.rear right wing'.tr(),
  'auto.front right wing'.tr(),
  'auto.front right tire'.tr(),
  'auto.rear right tire'.tr(),
  'auto.front left window'.tr(),
  'auto.rear left window'.tr(),
  'auto.front left door'.tr(),
  'auto.rear left door'.tr(),
  'auto.front left wing'.tr(),
  'auto.rear left wing'.tr(),
  'auto.front left tire'.tr(),
  'auto.rear left tire'.tr(),
  'auto.front right wheel'.tr(),
  'auto.ear right wheel'.tr(),
  'auto.front left wheel'.tr(),
  'auto.rear left wheel'.tr(),
];

List<String> _vanPartList = [
  'van.windscreen'.tr(),
  'van.roof'.tr(),
  'van.rear window'.tr(),
  'van.rear left headlight'.tr(),
  'van.rear right headlight'.tr(),
  'van.Rear bumpers'.tr(),
  'van.right side view mirror'.tr(),
  'van.left side view mirror'.tr(),
  'van.front right headlight'.tr(),
  'van.front left headlight'.tr(),
  'van.front grille'.tr(),
  'van.front bumpers'.tr(),
  'van.rear right window'.tr(),
  'van.front right window'.tr(),
  'van.front right door'.tr(),
  'van.rear right door'.tr(),
  'van.rear right wing'.tr(),
  'van.front right wing'.tr(),
  'van.front right tire'.tr(),
  'van.rear right tire'.tr(),
  'van.front left window'.tr(),
  'van.rear left window'.tr(),
  'van.front left door'.tr(),
  'van.Bonnet'.tr(),
  'van.rear left door'.tr(),
  'van.front left wing'.tr(),
  'van.rear left wing'.tr(),
  'van.front left tire'.tr(),
  'van.rear left tire'.tr(),
  'van.cargo door left'.tr(),
  'van.middle left window'.tr(),
  'van.middle right window'.tr(),
  'van.front right wheel'.tr(),
  'van.front left wheel'.tr(),
  'van.rear right wheel'.tr(),
  'van.rear left wheel'.tr(),
  'van.cargo door right'.tr(),
];

List<String> _motoPartList = [
  'byke.windshield'.tr(),
  'byke.handlebars'.tr(),
  'byke.headlight'.tr(),
  'byke.fuel tank'.tr(),
  'byke.seat'.tr(),
  'byke.tail light'.tr(),
  'byke.rear fender'.tr(),
  'byke.exhaust pipe'.tr(),
  'byke.left rear view mirror'.tr(),
  'byke.right rear view mirror'.tr(),
  'byke.front tire'.tr(),
  'byke.rear tire'.tr(),
  'byke.front fork'.tr(),
  'byke.rear swingarm'.tr(),
  'byke.throttle grip'.tr(),
  'byke.brake lever'.tr(),
  'byke.clutch lever'.tr(),
  'byke.sprocket'.tr(),
  'byke.engine'.tr(),
  'byke.front brake caliper'.tr(),
  'byke.rear brake caliper'.tr(),
];
