// Mocks generated by Mockito 5.4.4 from annotations
// in blinq/test/domain/repository/accident_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blinq/data/datasource/remote/accident_api.dart' as _i3;
import 'package:blinq/data/model/car/vehicle_type/vehicle_type.dart' as _i13;
import 'package:blinq/data/model/insurance/request/insurance_request_model.dart'
    as _i12;
import 'package:blinq/data/model/policy_holder/request/policy_holder_request_model.dart'
    as _i11;
import 'package:blinq/data/model/profile/request/profile_request_model.dart'
    as _i10;
import 'package:blinq/data/model/profile/response/profile_response_model.dart'
    as _i2;
import 'package:blinq/data/model/report/injury/injury.dart' as _i7;
import 'package:blinq/data/model/report/report_time_and_location/report_time_and_location.dart'
    as _i5;
import 'package:blinq/data/model/second_driver/car/request/second_driver_car_request_model.dart'
    as _i9;
import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponseModel_0 extends _i1.SmartFake
    implements _i2.ProfileResponseModel {
  _FakeProfileResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccidentApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccidentApi extends _i1.Mock implements _i3.AccidentApi {
  MockAccidentApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileResponseModel> fetchUserById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ProfileResponseModel>.value(
            _FakeProfileResponseModel_0(
          this,
          Invocation.method(
            #fetchUserById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ProfileResponseModel>);

  @override
  _i4.Future<void> addDriverB({
    required int? accidentId,
    required int? secondDriverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDriverB,
          [],
          {
            #accidentId: accidentId,
            #secondDriverId: secondDriverId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> createAccident(
    String? long,
    String? lat,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccident,
          [
            long,
            lat,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> addAccidentLocationAndTime(
    int? accidentId,
    _i5.ReportTimeAndLocationDto? accidentTimeAndLocationDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccidentLocationAndTime,
          [
            accidentId,
            accidentTimeAndLocationDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> uploadFile({required _i6.MultipartFile? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {#file: file},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> uploadAccidentSketch({
    required int? accidentId,
    required _i6.MultipartFile? sketch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAccidentSketch,
          [],
          {
            #accidentId: accidentId,
            #sketch: sketch,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentInjury(
    int? accidentId,
    _i7.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInjury,
          [
            accidentId,
            injuryDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentWitnesses(
    int? accidentId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentWitnesses,
          [
            accidentId,
            witnesses,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentInitialImpactPoint(
    int? accidentId,
    _i6.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInitialImpactPoint,
          [
            accidentId,
            image,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> visibleDamage(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamage,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> myRemarks(
    int? accidentId,
    String? myRemarks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarks,
          [
            accidentId,
            myRemarks,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> damagedPoints({
    required _i6.MultipartFile? top,
    required _i6.MultipartFile? front,
    required _i6.MultipartFile? back,
    required _i6.MultipartFile? left,
    required _i6.MultipartFile? right,
    required int? accidentId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPoints,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #accidentId: accidentId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadMedia(
    int? accidentId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            accidentId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sign(
    int? accidentId,
    _i6.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [
            accidentId,
            sign,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> connectToNoBlinqDriver(int? accidentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToNoBlinqDriver,
          [accidentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentInjuryB(
    int? accidentId,
    _i7.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInjuryB,
          [
            accidentId,
            injuryDto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentWitnessesB(
    int? accidentId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentWitnessesB,
          [
            accidentId,
            witnesses,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> accidentInitialImpactPointB(
    int? accidentId,
    _i6.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInitialImpactPointB,
          [
            accidentId,
            image,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> visibleDamageB(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamageB,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> myRemarksB(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarksB,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> damagedPointsB({
    required _i6.MultipartFile? top,
    required _i6.MultipartFile? front,
    required _i6.MultipartFile? back,
    required _i6.MultipartFile? left,
    required _i6.MultipartFile? right,
    required int? accidentId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPointsB,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #accidentId: accidentId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadMediaB(
    int? accidentId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMediaB,
          [
            accidentId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signB(
    int? accidentId,
    _i6.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signB,
          [
            accidentId,
            sign,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendCircumstances({
    required int? accidentId,
    required List<String>? a,
    required List<String>? b,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCircumstances,
          [],
          {
            #accidentId: accidentId,
            #a: a,
            #b: b,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getPdf(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #getPdf,
          [accidentId],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getPdf,
            [accidentId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> downloadFile({
    required String? path,
    required String? url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [],
          {
            #path: path,
            #url: url,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendToInsurance(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #sendToInsurance,
          [accidentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getAccidentStep(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #getAccidentStep,
          [accidentId],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getAccidentStep,
            [accidentId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateCarB(
    int? accidentId,
    _i9.SecondDriverCarRequestModel? secondDriverCarRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCarB,
          [
            accidentId,
            secondDriverCarRequestModel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDriverB(
    int? accidentId,
    _i10.ProfileRequestModel? profileRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDriverB,
          [
            accidentId,
            profileRequestModel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePolicyHolderB(
    int? accidentId,
    _i11.PolicyHolderRequestModel? policyHolderRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePolicyHolderB,
          [
            accidentId,
            policyHolderRequestModel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateInsuranceCompanyB(
    int? accidentId,
    _i12.InsuranceRequestModel? insuranceRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsuranceCompanyB,
          [
            accidentId,
            insuranceRequestModel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i13.VehicleType> getSecondDriverVehicleType(int? accidentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecondDriverVehicleType,
          [accidentId],
        ),
        returnValue: _i4.Future<_i13.VehicleType>.value(_i13.VehicleType.auto),
      ) as _i4.Future<_i13.VehicleType>);

  @override
  _i4.Future<void> deactivateAccident(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #deactivateAccident,
          [accidentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendNotificationToUserB({
    required int? accidentId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationToUserB,
          [],
          {
            #accidentId: accidentId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> respondToNotification({
    required int? accidentId,
    required bool? isAgree,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToNotification,
          [],
          {
            #accidentId: accidentId,
            #isAgree: isAgree,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i11.PolicyHolderRequestModel?> sameAsDriver({
    required int? accidentId,
    required bool? sameAsDriver,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sameAsDriver,
          [],
          {
            #accidentId: accidentId,
            #sameAsDriver: sameAsDriver,
          },
        ),
        returnValue: _i4.Future<_i11.PolicyHolderRequestModel?>.value(),
      ) as _i4.Future<_i11.PolicyHolderRequestModel?>);
}
