// Mocks generated by Mockito 5.4.4 from annotations
// in blinq/test/domain/repository/breakdown_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:blinq/data/datasource/remote/breakdown_api.dart' as _i2;
import 'package:blinq/data/model/report/injury/injury.dart' as _i7;
import 'package:blinq/data/model/report/report_time_and_location/report_time_and_location.dart'
    as _i5;
import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BreakdownApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreakdownApi extends _i1.Mock implements _i2.BreakdownApi {
  MockBreakdownApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createBreakdown(
    String? long,
    String? lat,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBreakdown,
          [
            long,
            lat,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> getBreakdownStep(int? breakdownId) => (super.noSuchMethod(
        Invocation.method(
          #getBreakdownStep,
          [breakdownId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getBreakdownStep,
            [breakdownId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> addBreakdownLocationAndTime(
    int? breakdownId,
    _i5.ReportTimeAndLocationDto? reportTimeAndLocationDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBreakdownLocationAndTime,
          [
            breakdownId,
            reportTimeAndLocationDto,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendCircumstances({
    required int? breakdownId,
    required List<String>? list,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCircumstances,
          [],
          {
            #breakdownId: breakdownId,
            #list: list,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getPdf(int? breakdownId) => (super.noSuchMethod(
        Invocation.method(
          #getPdf,
          [breakdownId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getPdf,
            [breakdownId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<int> uploadFile({required _i6.MultipartFile? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {#file: file},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> uploadBreakdownSketch({
    required int? breakdownId,
    required _i6.MultipartFile? sketch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBreakdownSketch,
          [],
          {
            #breakdownId: breakdownId,
            #sketch: sketch,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> breakdownInjury(
    int? breakdownId,
    _i7.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownInjury,
          [
            breakdownId,
            injuryDto,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> breakdownWitnesses(
    int? breakdownId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownWitnesses,
          [
            breakdownId,
            witnesses,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> breakdownInitialImpactPoint(
    int? breakdownId,
    _i6.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownInitialImpactPoint,
          [
            breakdownId,
            image,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> visibleDamage(
    int? breakdownId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamage,
          [
            breakdownId,
            visibleDamage,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> myRemarks(
    int? breakdownId,
    String? myRemarks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarks,
          [
            breakdownId,
            myRemarks,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> damagedPoints({
    required _i6.MultipartFile? top,
    required _i6.MultipartFile? front,
    required _i6.MultipartFile? back,
    required _i6.MultipartFile? left,
    required _i6.MultipartFile? right,
    required int? breakdownId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPoints,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #breakdownId: breakdownId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadMedia(
    int? breakdownId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            breakdownId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sign(
    int? breakdownId,
    _i6.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [
            breakdownId,
            sign,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deactivateBreakdown(int? breakdownId) => (super.noSuchMethod(
        Invocation.method(
          #deactivateBreakdown,
          [breakdownId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
