// Mocks generated by Mockito 5.4.2 from annotations
// in blinq/test/domain/repository/contacts_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:blinq/data/datasource/remote/contacts_api.dart' as _i4;
import 'package:blinq/data/model/contact/contact_response_dto.dart' as _i2;
import 'package:blinq/data/model/contact/request/contact_request_model.dart'
    as _i6;
import 'package:blinq/data/model/contact/response/contact_response_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContactResponseDto_0 extends _i1.SmartFake
    implements _i2.ContactResponseDto {
  _FakeContactResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactResponseModel_1 extends _i1.SmartFake
    implements _i3.ContactResponseModel {
  _FakeContactResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContactsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactsApi extends _i1.Mock implements _i4.ContactsApi {
  MockContactsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ContactResponseDto> fetchList([int? page]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchList,
          [page],
        ),
        returnValue:
            _i5.Future<_i2.ContactResponseDto>.value(_FakeContactResponseDto_0(
          this,
          Invocation.method(
            #fetchList,
            [page],
          ),
        )),
      ) as _i5.Future<_i2.ContactResponseDto>);

  @override
  _i5.Future<_i3.ContactResponseModel> add({
    required _i6.ContactRequestModel? contact,
    _i7.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {
            #contact: contact,
            #file: file,
          },
        ),
        returnValue: _i5.Future<_i3.ContactResponseModel>.value(
            _FakeContactResponseModel_1(
          this,
          Invocation.method(
            #add,
            [],
            {
              #contact: contact,
              #file: file,
            },
          ),
        )),
      ) as _i5.Future<_i3.ContactResponseModel>);

  @override
  _i5.Future<_i3.ContactResponseModel> update({
    required int? id,
    required _i6.ContactRequestModel? contact,
    _i7.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #id: id,
            #contact: contact,
            #file: file,
          },
        ),
        returnValue: _i5.Future<_i3.ContactResponseModel>.value(
            _FakeContactResponseModel_1(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #contact: contact,
              #file: file,
            },
          ),
        )),
      ) as _i5.Future<_i3.ContactResponseModel>);

  @override
  _i5.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
