// Mocks generated by Mockito 5.4.2 from annotations
// in blinq/test/domain/repository/premade_messages_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i5;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:blinq/data/datasource/remote/premade_messages_api.dart' as _i4;

import 'package:blinq/data/model/premade_message/premade_message_response_dto.dart'
    as _i2;
import 'package:blinq/data/model/premade_message/request/premade_message_request_model.dart'
    as _i6;
import 'package:blinq/data/model/premade_message/response/premade_message_response_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePreMadeMessageResponseDto_0 extends _i1.SmartFake
    implements _i2.PreMadeMessageResponseDto {
  _FakePreMadeMessageResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreMadeMessageResponseModel_1 extends _i1.SmartFake
    implements _i3.PreMadeMessageResponseModel {
  _FakePreMadeMessageResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PremadeMessagesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremadeMessagesApi extends _i1.Mock
    implements _i4.PremadeMessagesApi {
  MockPremadeMessagesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PreMadeMessageResponseDto> fetchList([int? count]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchList,
          [count],
        ),
        returnValue: _i5.Future<_i2.PreMadeMessageResponseDto>.value(
            _FakePreMadeMessageResponseDto_0(
          this,
          Invocation.method(
            #fetchList,
            [count],
          ),
        )),
      ) as _i5.Future<_i2.PreMadeMessageResponseDto>);

  @override
  _i5.Future<_i3.PreMadeMessageResponseModel> add(
          _i6.PreMadeMessageRequestModel? premadeMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [premadeMessage],
        ),
        returnValue: _i5.Future<_i3.PreMadeMessageResponseModel>.value(
            _FakePreMadeMessageResponseModel_1(
          this,
          Invocation.method(
            #add,
            [premadeMessage],
          ),
        )),
      ) as _i5.Future<_i3.PreMadeMessageResponseModel>);

  @override
  _i5.Future<_i3.PreMadeMessageResponseModel> update({
    required int? id,
    required _i6.PreMadeMessageRequestModel? premadeMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #id: id,
            #premadeMessage: premadeMessage,
          },
        ),
        returnValue: _i5.Future<_i3.PreMadeMessageResponseModel>.value(
            _FakePreMadeMessageResponseModel_1(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #premadeMessage: premadeMessage,
            },
          ),
        )),
      ) as _i5.Future<_i3.PreMadeMessageResponseModel>);

  @override
  _i5.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
