// Mocks generated by Mockito 5.4.5 from annotations
// in blinq/test/domain/repository/profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:io' as _i11;

import 'package:blinq/data/datasource/remote/profile_api.dart' as _i8;
import 'package:blinq/data/model/car/request/car_request_model.dart' as _i13;
import 'package:blinq/data/model/cheack_account_datas/cheack_account_datas_response.dart'
    as _i7;
import 'package:blinq/data/model/history/history_response_dto.dart' as _i3;
import 'package:blinq/data/model/insurance/request/insurance_request_model.dart'
    as _i15;
import 'package:blinq/data/model/policy_holder/request/policy_holder_request_model.dart'
    as _i12;
import 'package:blinq/data/model/profile/request/profile_request_model.dart'
    as _i10;
import 'package:blinq/data/model/profile/response/profile_response_model.dart'
    as _i2;
import 'package:blinq/data/model/vehicle/request/vehicle_request_model.dart'
    as _i14;
import 'package:blinq/data/model/vehicle_info/brand_response.dart' as _i4;
import 'package:blinq/data/model/vehicle_info/color/vehicle_color_dto.dart'
    as _i6;
import 'package:blinq/data/model/vehicle_info/color_response.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileResponseModel_0 extends _i1.SmartFake
    implements _i2.ProfileResponseModel {
  _FakeProfileResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHistoryResponseDto_1 extends _i1.SmartFake
    implements _i3.HistoryResponseDto {
  _FakeHistoryResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBrandResponseDto_2 extends _i1.SmartFake
    implements _i4.BrandResponseDto {
  _FakeBrandResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColorResponseDto_3 extends _i1.SmartFake
    implements _i5.ColorResponseDto {
  _FakeColorResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVehicleColorDto_4 extends _i1.SmartFake
    implements _i6.VehicleColorDto {
  _FakeVehicleColorDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckAccountResponse_5 extends _i1.SmartFake
    implements _i7.CheckAccountResponse {
  _FakeCheckAccountResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApi extends _i1.Mock implements _i8.ProfileApi {
  MockProfileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ProfileResponseModel> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue: _i9.Future<_i2.ProfileResponseModel>.value(
            _FakeProfileResponseModel_0(
          this,
          Invocation.method(
            #fetch,
            [],
          ),
        )),
      ) as _i9.Future<_i2.ProfileResponseModel>);

  @override
  _i9.Future<_i2.ProfileResponseModel> update(
          _i10.ProfileRequestModel? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [profile],
        ),
        returnValue: _i9.Future<_i2.ProfileResponseModel>.value(
            _FakeProfileResponseModel_0(
          this,
          Invocation.method(
            #update,
            [profile],
          ),
        )),
      ) as _i9.Future<_i2.ProfileResponseModel>);

  @override
  _i9.Future<void> updateProfileImage(_i11.File? file) => (super.noSuchMethod(
        Invocation.method(
          #updateProfileImage,
          [file],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updatePolicyHolder(
          _i12.PolicyHolderRequestModel? policyHolder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePolicyHolder,
          [policyHolder],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateCar(_i13.CarRequestModel? vehicle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCar,
          [vehicle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserVehicle(_i14.UserVehicleRequestModel? myVehicle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserVehicle,
          [myVehicle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateInsurance(_i15.InsuranceRequestModel? vehicle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsurance,
          [vehicle],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateMyCar(_i13.CarRequestModel? myCar) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyCar,
          [myCar],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updatePassword(
    String? oldPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [
            oldPassword,
            newPassword,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> verifyEmail(String? code) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [code],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [language],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.HistoryResponseDto> fetchHistory() => (super.noSuchMethod(
        Invocation.method(
          #fetchHistory,
          [],
        ),
        returnValue:
            _i9.Future<_i3.HistoryResponseDto>.value(_FakeHistoryResponseDto_1(
          this,
          Invocation.method(
            #fetchHistory,
            [],
          ),
        )),
      ) as _i9.Future<_i3.HistoryResponseDto>);

  @override
  _i9.Future<void> deleteReport(int? docId) => (super.noSuchMethod(
        Invocation.method(
          #deleteReport,
          [docId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> downloadReport({
    required String? url,
    required String? localPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadReport,
          [],
          {
            #url: url,
            #localPath: localPath,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.BrandResponseDto> fetchBrands(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBrands,
          [page],
        ),
        returnValue:
            _i9.Future<_i4.BrandResponseDto>.value(_FakeBrandResponseDto_2(
          this,
          Invocation.method(
            #fetchBrands,
            [page],
          ),
        )),
      ) as _i9.Future<_i4.BrandResponseDto>);

  @override
  _i9.Future<_i4.BrandResponseDto> fetchModels(
    int? page,
    int? brandId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchModels,
          [
            page,
            brandId,
          ],
        ),
        returnValue:
            _i9.Future<_i4.BrandResponseDto>.value(_FakeBrandResponseDto_2(
          this,
          Invocation.method(
            #fetchModels,
            [
              page,
              brandId,
            ],
          ),
        )),
      ) as _i9.Future<_i4.BrandResponseDto>);

  @override
  _i9.Future<_i5.ColorResponseDto> fetchColors(
    int? page,
    int? brandId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchColors,
          [
            page,
            brandId,
          ],
        ),
        returnValue:
            _i9.Future<_i5.ColorResponseDto>.value(_FakeColorResponseDto_3(
          this,
          Invocation.method(
            #fetchColors,
            [
              page,
              brandId,
            ],
          ),
        )),
      ) as _i9.Future<_i5.ColorResponseDto>);

  @override
  _i9.Future<_i6.VehicleColorDto> addColor(
    String? color,
    int? brandId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addColor,
          [
            color,
            brandId,
          ],
        ),
        returnValue:
            _i9.Future<_i6.VehicleColorDto>.value(_FakeVehicleColorDto_4(
          this,
          Invocation.method(
            #addColor,
            [
              color,
              brandId,
            ],
          ),
        )),
      ) as _i9.Future<_i6.VehicleColorDto>);

  @override
  _i9.Future<_i7.CheckAccountResponse> checkAccountData() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAccountData,
          [],
        ),
        returnValue: _i9.Future<_i7.CheckAccountResponse>.value(
            _FakeCheckAccountResponse_5(
          this,
          Invocation.method(
            #checkAccountData,
            [],
          ),
        )),
      ) as _i9.Future<_i7.CheckAccountResponse>);
}
