// Mocks generated by Mockito 5.4.2 from annotations
// in blinq/test/presentation/report/pages/damaged_media/cubit/damaged_media_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:blinq/data/model/car/vehicle_type/vehicle_type.dart' as _i9;
import 'package:blinq/data/model/insurance/request/insurance_request_model.dart'
    as _i18;
import 'package:blinq/data/model/policy_holder/request/policy_holder_request_model.dart'
    as _i17;
import 'package:blinq/data/model/profile/request/profile_request_model.dart'
    as _i16;
import 'package:blinq/data/model/profile/response/profile_response_model.dart'
    as _i6;
import 'package:blinq/data/model/report/injury/injury.dart' as _i14;
import 'package:blinq/data/model/report/report_time_and_location/report_time_and_location.dart'
    as _i12;
import 'package:blinq/data/model/second_driver/car/request/second_driver_car_request_model.dart'
    as _i15;
import 'package:blinq/domain/bloc/report_bloc/report_bloc.dart' as _i7;
import 'package:blinq/domain/bloc/report_bloc/report_bloc_state.dart' as _i5;
import 'package:blinq/domain/bloc/report_bloc/report_type.dart' as _i8;
import 'package:blinq/domain/repositories/accident_repository.dart' as _i2;
import 'package:blinq/domain/repositories/breakdown_repository.dart' as _i3;
import 'package:blinq/presentation/profile/bloc/profile_bloc.dart' as _i4;
import 'package:blinq/utils/services/media/media_service.dart' as _i19;
import 'package:dio/dio.dart' as _i13;
import 'package:flutter_bloc/flutter_bloc.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccidentRepository_0 extends _i1.SmartFake
    implements _i2.AccidentRepository {
  _FakeAccidentRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBreakdownRepository_1 extends _i1.SmartFake
    implements _i3.BreakdownRepository {
  _FakeBreakdownRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileBloc_2 extends _i1.SmartFake implements _i4.ProfileBloc {
  _FakeProfileBloc_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReportState_3 extends _i1.SmartFake implements _i5.ReportState {
  _FakeReportState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileResponseModel_4 extends _i1.SmartFake
    implements _i6.ProfileResponseModel {
  _FakeProfileResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReportBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportBloc extends _i1.Mock implements _i7.ReportBloc {
  MockReportBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccidentRepository get accidentRepository => (super.noSuchMethod(
        Invocation.getter(#accidentRepository),
        returnValue: _FakeAccidentRepository_0(
          this,
          Invocation.getter(#accidentRepository),
        ),
      ) as _i2.AccidentRepository);

  @override
  _i3.BreakdownRepository get breakdownRepository => (super.noSuchMethod(
        Invocation.getter(#breakdownRepository),
        returnValue: _FakeBreakdownRepository_1(
          this,
          Invocation.getter(#breakdownRepository),
        ),
      ) as _i3.BreakdownRepository);

  @override
  _i4.ProfileBloc get profileBloc => (super.noSuchMethod(
        Invocation.getter(#profileBloc),
        returnValue: _FakeProfileBloc_2(
          this,
          Invocation.getter(#profileBloc),
        ),
      ) as _i4.ProfileBloc);

  @override
  _i8.ReportType get reportType => (super.noSuchMethod(
        Invocation.getter(#reportType),
        returnValue: _i8.ReportType.accident,
      ) as _i8.ReportType);

  @override
  int get reportId => (super.noSuchMethod(
        Invocation.getter(#reportId),
        returnValue: 0,
      ) as int);

  @override
  _i9.VehicleType get aDriverVehicleType => (super.noSuchMethod(
        Invocation.getter(#aDriverVehicleType),
        returnValue: _i9.VehicleType.auto,
      ) as _i9.VehicleType);

  @override
  _i5.ReportState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeReportState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.ReportState);

  @override
  _i10.Stream<_i5.ReportState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i10.Stream<_i5.ReportState>.empty(),
      ) as _i10.Stream<_i5.ReportState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  dynamic setReportType(_i8.ReportType? type) =>
      super.noSuchMethod(Invocation.method(
        #setReportType,
        [type],
      ));

  @override
  dynamic setReportId(int? reportId) => super.noSuchMethod(Invocation.method(
        #setReportId,
        [reportId],
      ));

  @override
  dynamic setUser(_i8.User? user) => super.noSuchMethod(Invocation.method(
        #setUser,
        [user],
      ));

  @override
  _i10.Future<_i7.RouteAndArgs?> onCreateReport() => (super.noSuchMethod(
        Invocation.method(
          #onCreateReport,
          [],
        ),
        returnValue: _i10.Future<_i7.RouteAndArgs?>.value(),
      ) as _i10.Future<_i7.RouteAndArgs?>);

  @override
  _i10.Future<_i7.RouteAndArgs?> getReportStep(
    int? accidentId,
    _i8.ReportType? reportType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportStep,
          [
            accidentId,
            reportType,
          ],
        ),
        returnValue: _i10.Future<_i7.RouteAndArgs?>.value(),
      ) as _i10.Future<_i7.RouteAndArgs?>);

  @override
  void emit(_i5.ReportState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i5.ReportState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AccidentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccidentRepository extends _i1.Mock
    implements _i2.AccidentRepository {
  MockAccidentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.ProfileResponseModel> fetchUserById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserById,
          [id],
        ),
        returnValue: _i10.Future<_i6.ProfileResponseModel>.value(
            _FakeProfileResponseModel_4(
          this,
          Invocation.method(
            #fetchUserById,
            [id],
          ),
        )),
      ) as _i10.Future<_i6.ProfileResponseModel>);

  @override
  _i10.Future<void> addDriverB({
    required int? accidentId,
    required int? secondDriverId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDriverB,
          [],
          {
            #accidentId: accidentId,
            #secondDriverId: secondDriverId,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> createAccident(
    String? long,
    String? lat,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccident,
          [
            long,
            lat,
          ],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> addAccidentLocationAndTime(
    int? accidentId,
    _i12.ReportTimeAndLocationDto? accidentTimeAndLocationDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccidentLocationAndTime,
          [
            accidentId,
            accidentTimeAndLocationDto,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentSketch(
    int? accidentId,
    _i13.MultipartFile? sketch,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentSketch,
          [
            accidentId,
            sketch,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> uploadFile({required _i13.MultipartFile? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {#file: file},
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> sendCircumstances({
    required int? accidentId,
    required List<String>? a,
    required List<String>? b,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCircumstances,
          [],
          {
            #accidentId: accidentId,
            #a: a,
            #b: b,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentInjury(
    int? accidentId,
    _i14.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInjury,
          [
            accidentId,
            injuryDto,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentWitnesses(
    int? accidentId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentWitnesses,
          [
            accidentId,
            witnesses,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentInitialImpactPoint(
    int? accidentId,
    _i13.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInitialImpactPoint,
          [
            accidentId,
            image,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> visibleDamage(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamage,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> myRemarks(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarks,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> damagedPoints({
    required _i13.MultipartFile? top,
    required _i13.MultipartFile? front,
    required _i13.MultipartFile? back,
    required _i13.MultipartFile? left,
    required _i13.MultipartFile? right,
    required int? accidentId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPoints,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #accidentId: accidentId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadMedia(
    int? accidentId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            accidentId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sign(
    int? accidentId,
    _i13.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [
            accidentId,
            sign,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> connectToNoBlinqDriver(int? accidentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToNoBlinqDriver,
          [accidentId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentInjuryB(
    int? accidentId,
    _i14.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInjuryB,
          [
            accidentId,
            injuryDto,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentWitnessesB(
    int? accidentId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentWitnessesB,
          [
            accidentId,
            witnesses,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> accidentInitialImpactPointB(
    int? accidentId,
    _i13.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #accidentInitialImpactPointB,
          [
            accidentId,
            image,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> visibleDamageB(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamageB,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> myRemarksB(
    int? accidentId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarksB,
          [
            accidentId,
            visibleDamage,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> damagedPointsB({
    required _i13.MultipartFile? top,
    required _i13.MultipartFile? front,
    required _i13.MultipartFile? back,
    required _i13.MultipartFile? left,
    required _i13.MultipartFile? right,
    required int? accidentId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPointsB,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #accidentId: accidentId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadMediaB(
    int? accidentId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMediaB,
          [
            accidentId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> signB(
    int? accidentId,
    _i13.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signB,
          [
            accidentId,
            sign,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> getPdf(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #getPdf,
          [accidentId],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> downloadFile({
    required String? path,
    required String? url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [],
          {
            #path: path,
            #url: url,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sendToInsurance(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #sendToInsurance,
          [accidentId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> getAccidentStep(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #getAccidentStep,
          [accidentId],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> updateCarB(
    int? accidentId,
    _i15.SecondDriverCarRequestModel? secondDriverCarRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCarB,
          [
            accidentId,
            secondDriverCarRequestModel,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateDriverB(
    int? accidentId,
    _i16.ProfileRequestModel? profileRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDriverB,
          [
            accidentId,
            profileRequestModel,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updatePolicyHolderB(
    int? accidentId,
    _i17.PolicyHolderRequestModel? policyHolderRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePolicyHolderB,
          [
            accidentId,
            policyHolderRequestModel,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateInsuranceCompanyB(
    int? accidentId,
    _i18.InsuranceRequestModel? insuranceRequestModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInsuranceCompanyB,
          [
            accidentId,
            insuranceRequestModel,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i9.VehicleType> getSecondDriverVehicleType(int? accidentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecondDriverVehicleType,
          [accidentId],
        ),
        returnValue: _i10.Future<_i9.VehicleType>.value(_i9.VehicleType.auto),
      ) as _i10.Future<_i9.VehicleType>);

  @override
  _i10.Future<void> deactivateAccident(int? accidentId) => (super.noSuchMethod(
        Invocation.method(
          #deactivateAccident,
          [accidentId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sendNotificationToUserB({
    required int? accidentId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotificationToUserB,
          [],
          {
            #accidentId: accidentId,
            #userId: userId,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> respondToNotification({
    required int? accidentId,
    required bool? isAgree,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToNotification,
          [],
          {
            #accidentId: accidentId,
            #isAgree: isAgree,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [BreakdownRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreakdownRepository extends _i1.Mock
    implements _i3.BreakdownRepository {
  MockBreakdownRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<int> createBreakdown(
    String? long,
    String? lat,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBreakdown,
          [
            long,
            lat,
          ],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<String> getBreakdownStep(int? breakdownId) => (super.noSuchMethod(
        Invocation.method(
          #getBreakdownStep,
          [breakdownId],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);

  @override
  _i10.Future<void> addBreakdownLocationAndTime(
    int? breakdownId,
    _i12.ReportTimeAndLocationDto? reportTimeAndLocationDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBreakdownLocationAndTime,
          [
            breakdownId,
            reportTimeAndLocationDto,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sendCircumstances({
    required int? breakdownId,
    required List<String>? list,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCircumstances,
          [],
          {
            #breakdownId: breakdownId,
            #list: list,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String> getPdf(int? breakdownId) => (super.noSuchMethod(
        Invocation.method(
          #getPdf,
          [breakdownId],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);

  @override
  _i10.Future<int> uploadFile({required _i13.MultipartFile? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {#file: file},
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> uploadBreakdownSketch({
    required int? breakdownId,
    required _i13.MultipartFile? sketch,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBreakdownSketch,
          [],
          {
            #breakdownId: breakdownId,
            #sketch: sketch,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> breakdownInjury(
    int? breakdownId,
    _i14.InjuryDto? injuryDto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownInjury,
          [
            breakdownId,
            injuryDto,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> breakdownWitnesses(
    int? breakdownId,
    String? witnesses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownWitnesses,
          [
            breakdownId,
            witnesses,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> breakdownInitialImpactPoint(
    int? breakdownId,
    _i13.MultipartFile? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #breakdownInitialImpactPoint,
          [
            breakdownId,
            image,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> visibleDamage(
    int? breakdownId,
    String? visibleDamage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #visibleDamage,
          [
            breakdownId,
            visibleDamage,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> myRemarks(
    int? breakdownId,
    String? myRemarks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #myRemarks,
          [
            breakdownId,
            myRemarks,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> damagedPoints({
    required _i13.MultipartFile? top,
    required _i13.MultipartFile? front,
    required _i13.MultipartFile? back,
    required _i13.MultipartFile? left,
    required _i13.MultipartFile? right,
    required int? breakdownId,
    required List<String>? damageParts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #damagedPoints,
          [],
          {
            #top: top,
            #front: front,
            #back: back,
            #left: left,
            #right: right,
            #breakdownId: breakdownId,
            #damageParts: damageParts,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uploadMedia(
    int? breakdownId,
    List<int>? uploadedFilesId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMedia,
          [
            breakdownId,
            uploadedFilesId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> sign(
    int? breakdownId,
    _i13.MultipartFile? sign,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [
            breakdownId,
            sign,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deactivateBreakdown(int? breakdownId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateBreakdown,
          [breakdownId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [MediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaService extends _i1.Mock implements _i19.MediaService {
  MockMediaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String?> pickImagePath(_i19.AppImageSource? appImageSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImagePath,
          [appImageSource],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<List<String>?> pickMultipleImagesPaths() => (super.noSuchMethod(
        Invocation.method(
          #pickMultipleImagesPaths,
          [],
        ),
        returnValue: _i10.Future<List<String>?>.value(),
      ) as _i10.Future<List<String>?>);

  @override
  _i10.Future<String?> pickVideoPath(_i19.AppImageSource? appImageSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideoPath,
          [appImageSource],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<String?> pickMediaPath({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMediaPath,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
          },
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<List<String>?> pickMultipleMediaPaths({
    double? maxHeight,
    double? maxWidth,
    int? imageQuality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMediaPaths,
          [],
          {
            #maxHeight: maxHeight,
            #maxWidth: maxWidth,
            #imageQuality: imageQuality,
          },
        ),
        returnValue: _i10.Future<List<String>?>.value(),
      ) as _i10.Future<List<String>?>);
}
