// Mocks generated by Mockito 5.4.4 from annotations
// in blinq/test/presentation/contacts/editors/contact/bloc/contact_edit_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:blinq/data/model/contact/contact_response_dto.dart' as _i4;
import 'package:blinq/data/model/contact/request/contact_request_model.dart'
    as _i9;
import 'package:blinq/data/model/contact/response/contact_response_model.dart'
    as _i5;
import 'package:blinq/domain/repositories/contacts_repository.dart' as _i2;
import 'package:blinq/presentation/contacts/pages/contacts/bloc/contacts_bloc.dart'
    as _i3;
import 'package:blinq/presentation/contacts/pages/contacts/bloc/contacts_event.dart'
    as _i7;
import 'package:blinq/utils/services/media/media_service.dart' as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContactsRepository_0 extends _i1.SmartFake
    implements _i2.ContactsRepository {
  _FakeContactsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactsState_1 extends _i1.SmartFake implements _i3.ContactsState {
  _FakeContactsState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactResponseDto_2 extends _i1.SmartFake
    implements _i4.ContactResponseDto {
  _FakeContactResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactResponseModel_3 extends _i1.SmartFake
    implements _i5.ContactResponseModel {
  _FakeContactResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContactsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactsBloc extends _i1.Mock implements _i3.ContactsBloc {
  MockContactsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ContactsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeContactsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ContactsRepository);

  @override
  _i3.ContactsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeContactsState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.ContactsState);

  @override
  _i6.Stream<_i3.ContactsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i3.ContactsState>.empty(),
      ) as _i6.Stream<_i3.ContactsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void onEditPressed({int? id}) => super.noSuchMethod(
        Invocation.method(
          #onEditPressed,
          [],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPhoneCall(String? phoneNumber) => super.noSuchMethod(
        Invocation.method(
          #onPhoneCall,
          [phoneNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onMessage(String? phoneNumber) => super.noSuchMethod(
        Invocation.method(
          #onMessage,
          [phoneNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i7.ContactsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i7.ContactsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.ContactsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i7.ContactsEvent>(
    _i8.EventHandler<E, _i3.ContactsState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i8.Transition<_i7.ContactsEvent, _i3.ContactsState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i7.ContactsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i3.ContactsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ContactsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactsRepository extends _i1.Mock
    implements _i2.ContactsRepository {
  MockContactsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ContactResponseDto> fetchList([int? page]) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchList,
          [page],
        ),
        returnValue:
            _i6.Future<_i4.ContactResponseDto>.value(_FakeContactResponseDto_2(
          this,
          Invocation.method(
            #fetchList,
            [page],
          ),
        )),
      ) as _i6.Future<_i4.ContactResponseDto>);

  @override
  _i6.Future<_i5.ContactResponseModel> add({
    required _i9.ContactRequestModel? contact,
    _i10.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {
            #contact: contact,
            #file: file,
          },
        ),
        returnValue: _i6.Future<_i5.ContactResponseModel>.value(
            _FakeContactResponseModel_3(
          this,
          Invocation.method(
            #add,
            [],
            {
              #contact: contact,
              #file: file,
            },
          ),
        )),
      ) as _i6.Future<_i5.ContactResponseModel>);

  @override
  _i6.Future<void> addList({required List<_i9.ContactRequestModel>? contact}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addList,
          [],
          {#contact: contact},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.ContactResponseModel> update({
    required int? id,
    required _i9.ContactRequestModel? contact,
    _i10.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #id: id,
            #contact: contact,
            #file: file,
          },
        ),
        returnValue: _i6.Future<_i5.ContactResponseModel>.value(
            _FakeContactResponseModel_3(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #contact: contact,
              #file: file,
            },
          ),
        )),
      ) as _i6.Future<_i5.ContactResponseModel>);

  @override
  _i6.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [MediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaService extends _i1.Mock implements _i11.MediaService {
  MockMediaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> pickImagePath(_i11.AppImageSource? appImageSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImagePath,
          [appImageSource],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<List<String>?> pickMultipleImagesPaths() => (super.noSuchMethod(
        Invocation.method(
          #pickMultipleImagesPaths,
          [],
        ),
        returnValue: _i6.Future<List<String>?>.value(),
      ) as _i6.Future<List<String>?>);

  @override
  _i6.Future<String?> pickVideoPath(_i11.AppImageSource? appImageSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideoPath,
          [appImageSource],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> pickMediaPath({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMediaPath,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
          },
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<List<String>?> pickMultipleMediaPaths({
    double? maxHeight,
    double? maxWidth,
    int? imageQuality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMediaPaths,
          [],
          {
            #maxHeight: maxHeight,
            #maxWidth: maxWidth,
            #imageQuality: imageQuality,
          },
        ),
        returnValue: _i6.Future<List<String>?>.value(),
      ) as _i6.Future<List<String>?>);
}
